#See blog post how to change name of SkyFanDC device at www.egglec.com.au
substitutions:
  device_name: easy-skyfandc #Device name on network
  fan_name: Fan #Name of fan entity in home assistant
  fan_light: Light #Name of light entity in home assistant
  light_color: Light-Color #Name of light color entity in home assistant
esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  project:
    name: jimmy.easy_skyfandc
    version: "2022.12.3"
      
esp8266:
  board: d1_mini

api:

# Logger not using the serial port as tuya needs it
logger:
  baud_rate: 0

# Version 0.2 has an i2c JST SH 4Pin Plug and uses the following pins
# Version 0.1 did use pin 4 as the power pin for the NTC
i2c:
  sda: 4
  scl: 5
  scan: true
ota:

wifi: #See blog post how to change name of device at www.egglec.com.au
  ap:
    password: ""
    
captive_portal:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  
tuya:

fan:
  - platform: tuya
    name: ${fan_name}
    switch_datapoint: 1
    speed_datapoint: 3
    direction_datapoint: 8
    speed_count: 6
    
light:
  - platform: "tuya"
    name: ${fan_light}
    dimmer_datapoint: 16
    min_value: 1
    max_value: 5
    switch_datapoint: 15

select:
  - platform: "tuya"
    name: ${light_color}
    enum_datapoint: 19
    optimistic: true
    options:
      0: CW
      1: NW
      2: WW
